/*
 * Created on 2024-06-08 ( 13:47:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.dragon.yunpeng.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Countries"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="COUNTRIES", schema="HR" )
public class Countries implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="COUNTRY_ID", nullable=false, length=2)
    private String     countryId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="COUNTRY_NAME", length=60)
    private String     countryName ;

    @Column(name="REGION_ID")
    private BigDecimal regionId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="countries")
    private List<Locations> listOfLocations ; 

    @ManyToOne
    @JoinColumn(name="REGION_ID", referencedColumnName="REGION_ID", insertable=false, updatable=false)
    private Regions    regions ; 


    /**
     * Constructor
     */
    public Countries() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setCountryId( String countryId ) {
        this.countryId = countryId ;
    }
    public String getCountryId() {
        return this.countryId;
    }

    public void setCountryName( String countryName ) {
        this.countryName = countryName ;
    }
    public String getCountryName() {
        return this.countryName;
    }

    public void setRegionId( BigDecimal regionId ) {
        this.regionId = regionId ;
    }
    public BigDecimal getRegionId() {
        return this.regionId;
    }

    //--- GETTERS FOR LINKS
    public List<Locations> getListOfLocations() {
        return this.listOfLocations;
    } 

    public Regions getRegions() {
        return this.regions;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(countryId);
        sb.append("|");
        sb.append(countryName);
        sb.append("|");
        sb.append(regionId);
        return sb.toString(); 
    } 

}
