/*
 * Created on 2024-06-08 ( 13:47:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.dragon.yunpeng.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Departments"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="DEPARTMENTS", schema="HR" )
public class Departments implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="DEPARTMENT_ID", nullable=false)
    private BigDecimal departmentId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="DEPARTMENT_NAME", nullable=false, length=30)
    private String     departmentName ;

    @Column(name="MANAGER_ID")
    private BigDecimal managerId ;

    @Column(name="LOCATION_ID")
    private BigDecimal locationId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="MANAGER_ID", referencedColumnName="EMPLOYEE_ID", insertable=false, updatable=false)
    private Employees  employees ; 

    @OneToMany(mappedBy="departments")
    private List<Employees> listOfEmployees ; 

    @ManyToOne
    @JoinColumn(name="LOCATION_ID", referencedColumnName="LOCATION_ID", insertable=false, updatable=false)
    private Locations  locations ; 

    @OneToMany(mappedBy="departments")
    private List<JobHistory> listOfJobHistory ; 


    /**
     * Constructor
     */
    public Departments() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setDepartmentId( BigDecimal departmentId ) {
        this.departmentId = departmentId ;
    }
    public BigDecimal getDepartmentId() {
        return this.departmentId;
    }

    public void setDepartmentName( String departmentName ) {
        this.departmentName = departmentName ;
    }
    public String getDepartmentName() {
        return this.departmentName;
    }

    public void setManagerId( BigDecimal managerId ) {
        this.managerId = managerId ;
    }
    public BigDecimal getManagerId() {
        return this.managerId;
    }

    public void setLocationId( BigDecimal locationId ) {
        this.locationId = locationId ;
    }
    public BigDecimal getLocationId() {
        return this.locationId;
    }

    //--- GETTERS FOR LINKS
    public Employees getEmployees() {
        return this.employees;
    } 

    public List<Employees> getListOfEmployees() {
        return this.listOfEmployees;
    } 

    public Locations getLocations() {
        return this.locations;
    } 

    public List<JobHistory> getListOfJobHistory() {
        return this.listOfJobHistory;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(departmentId);
        sb.append("|");
        sb.append(departmentName);
        sb.append("|");
        sb.append(managerId);
        sb.append("|");
        sb.append(locationId);
        return sb.toString(); 
    } 

}
