/*
 * Created on 2024-06-08 ( 13:47:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.dragon.yunpeng.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Employees"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="EMPLOYEES", schema="HR" )
public class Employees implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="EMPLOYEE_ID", nullable=false)
    private BigDecimal employeeId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="FIRST_NAME", length=20)
    private String     firstName ;

    @Column(name="LAST_NAME", nullable=false, length=25)
    private String     lastName ;

    @Column(name="EMAIL", nullable=false, length=25)
    private String     email ;

    @Column(name="PHONE_NUMBER", length=20)
    private String     phoneNumber ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="HIRE_DATE", nullable=false)
    private Date       hireDate ;

    @Column(name="JOB_ID", nullable=false, length=10)
    private String     jobId ;

    @Column(name="SALARY")
    private BigDecimal salary ;

    @Column(name="COMMISSION_PCT")
    private BigDecimal commissionPct ;

    @Column(name="MANAGER_ID")
    private BigDecimal managerId ;

    @Column(name="DEPARTMENT_ID")
    private BigDecimal departmentId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="employees")
    private List<Employees> listOfEmployees ; 

    @ManyToOne
    @JoinColumn(name="JOB_ID", referencedColumnName="JOB_ID", insertable=false, updatable=false)
    private Jobs       jobs ; 

    @ManyToOne
    @JoinColumn(name="MANAGER_ID", referencedColumnName="EMPLOYEE_ID", insertable=false, updatable=false)
    private Employees  employees ; 

    @OneToMany(mappedBy="employees")
    private List<JobHistory> listOfJobHistory ; 

    @OneToMany(mappedBy="employees")
    private List<Departments> listOfDepartments ; 

    @ManyToOne
    @JoinColumn(name="DEPARTMENT_ID", referencedColumnName="DEPARTMENT_ID", insertable=false, updatable=false)
    private Departments departments ; 


    /**
     * Constructor
     */
    public Employees() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setEmployeeId( BigDecimal employeeId ) {
        this.employeeId = employeeId ;
    }
    public BigDecimal getEmployeeId() {
        return this.employeeId;
    }

    public void setFirstName( String firstName ) {
        this.firstName = firstName ;
    }
    public String getFirstName() {
        return this.firstName;
    }

    public void setLastName( String lastName ) {
        this.lastName = lastName ;
    }
    public String getLastName() {
        return this.lastName;
    }

    public void setEmail( String email ) {
        this.email = email ;
    }
    public String getEmail() {
        return this.email;
    }

    public void setPhoneNumber( String phoneNumber ) {
        this.phoneNumber = phoneNumber ;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setHireDate( Date hireDate ) {
        this.hireDate = hireDate ;
    }
    public Date getHireDate() {
        return this.hireDate;
    }

    public void setJobId( String jobId ) {
        this.jobId = jobId ;
    }
    public String getJobId() {
        return this.jobId;
    }

    public void setSalary( BigDecimal salary ) {
        this.salary = salary ;
    }
    public BigDecimal getSalary() {
        return this.salary;
    }

    public void setCommissionPct( BigDecimal commissionPct ) {
        this.commissionPct = commissionPct ;
    }
    public BigDecimal getCommissionPct() {
        return this.commissionPct;
    }

    public void setManagerId( BigDecimal managerId ) {
        this.managerId = managerId ;
    }
    public BigDecimal getManagerId() {
        return this.managerId;
    }

    public void setDepartmentId( BigDecimal departmentId ) {
        this.departmentId = departmentId ;
    }
    public BigDecimal getDepartmentId() {
        return this.departmentId;
    }

    //--- GETTERS FOR LINKS
    public List<Employees> getListOfEmployees() {
        return this.listOfEmployees;
    } 

    public Jobs getJobs() {
        return this.jobs;
    } 

    public Employees getEmployees() {
        return this.employees;
    } 

    public List<JobHistory> getListOfJobHistory() {
        return this.listOfJobHistory;
    } 

    public List<Departments> getListOfDepartments() {
        return this.listOfDepartments;
    } 

    public Departments getDepartments() {
        return this.departments;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(employeeId);
        sb.append("|");
        sb.append(firstName);
        sb.append("|");
        sb.append(lastName);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(phoneNumber);
        sb.append("|");
        sb.append(hireDate);
        sb.append("|");
        sb.append(jobId);
        sb.append("|");
        sb.append(salary);
        sb.append("|");
        sb.append(commissionPct);
        sb.append("|");
        sb.append(managerId);
        sb.append("|");
        sb.append(departmentId);
        return sb.toString(); 
    } 

}
