/*
 * Created on 2024-06-08 ( 13:47:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.dragon.yunpeng.entities;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

/**
 * JPA entity class for "JobHistory"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="JOB_HISTORY", schema="HR" )
@IdClass(JobHistoryId.class)
public class JobHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="EMPLOYEE_ID", nullable=false)
    private BigDecimal employeeId ;

    @Id
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="START_DATE", nullable=false)
    private Date       startDate ;

    //--- ENTITY DATA FIELDS 
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_DATE", nullable=false)
    private Date       endDate ;

    @Column(name="JOB_ID", nullable=false, length=10)
    private String     jobId ;

    @Column(name="DEPARTMENT_ID")
    private BigDecimal departmentId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="EMPLOYEE_ID", referencedColumnName="EMPLOYEE_ID", insertable=false, updatable=false)
    private Employees  employees ; 

    @ManyToOne
    @JoinColumn(name="DEPARTMENT_ID", referencedColumnName="DEPARTMENT_ID", insertable=false, updatable=false)
    private Departments departments ; 

    @ManyToOne
    @JoinColumn(name="JOB_ID", referencedColumnName="JOB_ID", insertable=false, updatable=false)
    private Jobs       jobs ; 


    /**
     * Constructor
     */
    public JobHistory() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setEmployeeId( BigDecimal employeeId ) {
        this.employeeId = employeeId ;
    }
    public BigDecimal getEmployeeId() {
        return this.employeeId;
    }

    public void setStartDate( Date startDate ) {
        this.startDate = startDate ;
    }
    public Date getStartDate() {
        return this.startDate;
    }

    public void setEndDate( Date endDate ) {
        this.endDate = endDate ;
    }
    public Date getEndDate() {
        return this.endDate;
    }

    public void setJobId( String jobId ) {
        this.jobId = jobId ;
    }
    public String getJobId() {
        return this.jobId;
    }

    public void setDepartmentId( BigDecimal departmentId ) {
        this.departmentId = departmentId ;
    }
    public BigDecimal getDepartmentId() {
        return this.departmentId;
    }

    //--- GETTERS FOR LINKS
    public Employees getEmployees() {
        return this.employees;
    } 

    public Departments getDepartments() {
        return this.departments;
    } 

    public Jobs getJobs() {
        return this.jobs;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(employeeId);
        sb.append("|");
        sb.append(startDate);
        sb.append("|");
        sb.append(endDate);
        sb.append("|");
        sb.append(jobId);
        sb.append("|");
        sb.append(departmentId);
        return sb.toString(); 
    } 

}
