/*
 * Created on 2024-06-08 ( 13:47:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.dragon.yunpeng.entities;

import java.io.Serializable;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Composite primary key for entity "JobHistory" ( stored in table "JOB_HISTORY" )
 *
 * @author Telosys
 *
 */
public class JobHistoryId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private BigDecimal employeeId ;
    
    private Date       startDate ;
    
    /**
     * Constructor
     */
    public JobHistoryId() {
        super();
    }

    /**
     * Constructor with values
     * @param employeeId 
     * @param startDate 
     */
    public JobHistoryId( BigDecimal employeeId, Date startDate ) {
        super();
        this.employeeId = employeeId ;
        this.startDate = startDate ;
    }
    
    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setEmployeeId( BigDecimal value ) {
        this.employeeId = value;
    }
    public BigDecimal getEmployeeId() {
        return this.employeeId;
    }

    public void setStartDate( Date value ) {
        this.startDate = value;
    }
    public Date getStartDate() {
        return this.startDate;
    }


    //--- equals METHOD
	@Override
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		JobHistoryId other = (JobHistoryId) obj; 
		//--- Attribute employeeId
		if ( employeeId == null ) { 
			if ( other.employeeId != null ) 
				return false ; 
		} else if ( ! employeeId.equals(other.employeeId) ) 
			return false ; 
		//--- Attribute startDate
		if ( startDate == null ) { 
			if ( other.startDate != null ) 
				return false ; 
		} else if ( ! startDate.equals(other.startDate) ) 
			return false ; 
		return true; 
	} 

    //--- hashCode METHOD
	@Override
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute employeeId
		result = prime * result + ((employeeId == null) ? 0 : employeeId.hashCode() ) ; 
		//--- Attribute startDate
		result = prime * result + ((startDate == null) ? 0 : startDate.hashCode() ) ; 
		
		return result; 
	} 

    //--- toString METHOD
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(employeeId);
        sb.append("|");
        sb.append(startDate);
        return sb.toString(); 
    } 

}
